# Generated by Django 3.0.8 on 2020-08-04 00:41

from django.db import migrations
import ls.joyous.utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joyous', '0015_auto_20190409_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullCalendarPage',
            fields=[
            ],
            options={
                'verbose_name': 'calendar page',
                'verbose_name_plural': 'calendar pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ls.joyous.utils.mixins.ProxyPageMixin, 'joyous.calendarpage'),
        ),
    ]
