# Generated by Django 3.0.8 on 2020-08-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyful', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullcalendarpage',
            options={'verbose_name': 'full calendar page', 'verbose_name_plural': 'full calendar pages'},
        ),
    ]
